### ISSUE TITLE
Not found 

### ISSUE THREAD

**Issue by inteldon** [hirle/colored-led#8]
I tried running the npm install --save ColoredLed command, but I got this error:

`
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/ColorLed - Not found
npm ERR! 404
npm ERR! 404  'ColorLed@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can no longer contain capital letters`

**Comment by erichirlemann** [comment]
Instead `npm install --save colored-led` works.

**Comment by hirle** [comment]
True, thank for raising. This is now fixed.
